name: ChooseBrowser
options:
  bundleIdPrefix: com.choosebrowser
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    DEAD_CODE_STRIPPING: "YES"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
targets:
  ChooseBrowser:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Core
      - path: Routing
      - path: Discovery
      - path: Execution
      - path: Store
      - path: UI
      - path: Support
      - path: UI/Assets.xcassets
    info:
      path: App/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleURLTypes:
          - CFBundleTypeRole: Viewer
            CFBundleURLName: com.choosebrowser.http-https
            CFBundleURLSchemes:
              - http
              - https
        CFBundleShortVersionString: "0.1.4"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        LSUIElement: false
        NSPrincipalClass: NSApplication
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.app
        PRODUCT_NAME: ChooseBrowser
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  LinkSink:
    type: application
    platform: macOS
    sources:
      - path: Integration/LinkSink
    info:
      path: Integration/LinkSink/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "0.1.4"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        LSUIElement: true
        NSPrincipalClass: NSApplication
        CFBundleURLTypes:
          - CFBundleTypeRole: Viewer
            CFBundleURLName: com.choosebrowser.linksink.http-https
            CFBundleURLSchemes:
              - http
              - https
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.linksink
        PRODUCT_NAME: LinkSink
  SafariBridgeHost:
    type: tool
    platform: macOS
    sources:
      - path: Adapters/SafariBridgeHost
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.safaribridgehost
        PRODUCT_NAME: SafariBridgeHost
  NativeMessagingHost:
    type: tool
    platform: macOS
    sources:
      - path: Adapters/NativeMessagingHost
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.nativemessaginghost
        PRODUCT_NAME: NativeMessagingHost
  ChooseBrowserTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ChooseBrowserTests
    dependencies:
      - target: ChooseBrowser
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.tests
        PRODUCT_NAME: ChooseBrowserTests
  ChooseBrowserIntegrationTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ChooseBrowserIntegrationTests
    dependencies:
      - target: ChooseBrowser
      - target: LinkSink
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.integrationtests
        PRODUCT_NAME: ChooseBrowserIntegrationTests
  ChooseBrowserUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Tests/ChooseBrowserUITests
    dependencies:
      - target: ChooseBrowser
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.choosebrowser.uitests
        PRODUCT_NAME: ChooseBrowserUITests
schemes:
  ChooseBrowser:
    build:
      targets:
        ChooseBrowser: all
    test:
      targets:
        - name: ChooseBrowserTests
        - name: ChooseBrowserIntegrationTests
        - name: ChooseBrowserUITests
    run:
      config: Debug
  ChooseBrowserTests:
    build:
      targets:
        ChooseBrowserTests: all
    test:
      targets:
        - name: ChooseBrowserTests
  ChooseBrowserIntegrationTests:
    build:
      targets:
        LinkSink: all
        ChooseBrowserIntegrationTests: all
    test:
      targets:
        - name: ChooseBrowserIntegrationTests
  ChooseBrowserUITests:
    build:
      targets:
        ChooseBrowserUITests: all
    test:
      targets:
        - name: ChooseBrowserUITests
